language: ruby
cache: bundler

rvm:
  - 2.1.2

script: 'bundle exec rake'
cache: true

after_success:
  coveralls

notifications:
  email:
    recipients:
      - john.knott@gmail.com
    on_failure: change
    on_success: never